{% set name = "pychemist" %}
# Fixed version hardcoded to avoid environment issues
package:
  name: {{ name|lower }}
  version: 0.0.2

source:
  path: ../  # relative path to your package root

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pandas >=2.0

test:
  imports:
    - pychemist
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Transform raw data into insights.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jraak